packages:
  darwin:
    brews:
      - "fzf-tab"
      - "zsh-fast-syntax-highlighting"
      - "zsh-autosuggestions"
      - "uv"
      - "oh-my-posh"
      - "thefuck"
      - "eza"
      - "zoxide"
      - "tree"
      - "nanorc"
      - "gh"
    casks:
      - "font-jetbrains-mono-nerd-font"
      - "bitwarden"
      - "visual-studio-code"
  windows:
    winget:
      - "Microsoft.VisualStudioCode"
      - "Bitwarden.Bitwarden"
      - "astral-sh.uv"
      - "oh-my-posh.oh-my-posh"
      - "GitHub.cli"
